version: 0.2

run-as: root

buildjob:
  stage: build
  scripts:
    - docker build -t sathvikns/hello:version1 .
    - docker image push sathvikns/hello:version1
    - aws ecs update-service --cluster pythonflask --service flask-service --force-new-deployment
